name: "Terraform - Kubernetes Multi-cloud Lab"

on:
  # push:
  #   branches:
  #     - main

  # schedule:
  #   # Runs at 07:00 AM in every month.
  #   - cron: "0 17 */1 * *"

  # Optional: You can also allow manual runs
  workflow_dispatch:
    inputs:
      # -------------- AZURE --------------

      deploy_azure:
        description: "Azure Deploy ?"
        required: true
        default: false
        type: boolean

      azure_inputsets:
        description: "Choose inputSets for Azure"
        required: true
        default: "Azure_JapanEast_Plan"
        type: choice
        options:
          - Azure_JapanEast_Plan
          - Azure_JapanEast_Apply
          - Azure_JapanEast_Destroy
          - Azure_EastUS2_Plan_Destroy

      # -------------- AWS --------------

      deploy_aws:
        description: "AWS Deploy ?"
        required: true
        default: false
        type: boolean

      aws_inputsets:
        description: "Choose inputSets for AWS"
        required: true
        default: "AWS_us-east-1_Plan"
        type: choice
        options:
          - AWS_us-east-1_Plan
          - AWS_us-east-1_Apply
          - AWS_us-east-1_Destroy
          - AWS_us-west-2_Plan_Destroy

      # -------------- HCP --------------

      deploy_hcp:
        description: "HCP Deploy ?"
        required: true
        default: false
        type: boolean

      hcp_inputsets:
        description: "Choose inputSets for HCP"
        required: true
        default: "HCP_us-east-1_Plan"
        type: choice
        options:
          - HCP_us-east-1_Plan
          - HCP_us-east-1_Apply
          - HCP_us-east-1_Destroy
          - HCP_us-west-2_Plan_Destroy

env:
  Dummy_Env: "This is dummy env"

jobs:
  verify-configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: AZURE - Read JSON input set
        if: ${{ github.event.inputs.deploy_azure == 'true' }}
        id: inputset
        run: |
          content=$(cat .github/terraform--lab-cloud-k8s/inputsets/${{ github.event.inputs.azure_inputsets }}.json | jq -c .)
          echo "json=$content" >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          echo "Input JSON"
          echo "${{ steps.inputset.outputs.json }}"
          echo "----"
          echo "{\"ref\":\"main\",\"inputs\":${{ steps.inputset.outputs.json }}}"
          echo "----"
          echo "${{ github.repository }}"

      - name: AZURE - Trigger deploy workflow
        if: ${{ github.event.inputs.deploy_azure == 'true' }}
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: "terraform_deploy_kubernetes_single_cloud"
          client-payload: |
            {"ref":"main","inputs":${{ steps.inputset.outputs.json }}}
