name: 1password Update Credentials
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["[Kubernetes] OSS Installation"]
    types:
      - completed
env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONEPASSWORD_SERVICE_ACCOUNT_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  verify-configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Secret
        run: |
          echo "OP_SERVICE_ACCOUNT_TOKEN: ${OP_SERVICE_ACCOUNT_TOKEN:0:4}****"
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:4}****"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:0:4}****"
  onePassword-credential-update:
    runs-on: ubuntu-latest
    steps:
      - name: Install Kubectl
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/kubectl.sh | sh

      - name: Set up Cluster Access Credentials
        run: |
          aws s3 cp "s3://terragrunt-output/dev/azure/Japan East/kubeconfig" ~/.kube/config

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v2
        with:
          version: 2.22.0

      - name: Run test
        run: |
          ARGOCD_INIT_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          JENKINS_INIT_PASSWORD=$(kubectl get secret jenkins -n jenkins -o yaml | yq '.data."jenkins-admin-password"' | base64 --decode)
          op item edit "[Lab] Jenkins (local)" --vault="Temporary" "password=$JENKINS_INIT_PASSWORD"
          op item edit "[Lab] ArgoCD (local)" --vault="Temporary" "password=$ARGOCD_INIT_PASSWORD"
