name: 1password Test
on:
  workflow_dispatch:
env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  pass-credential-update:
    runs-on: ubuntu-latest
    steps:
      - name: Install Kubectl
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/kubectl.sh | sh

      - name: Set up Cluster Access Credentials
        run: |
          aws s3 cp "s3://terragrunt-output/dev/azure/Japan East/kubeconfig" ~/.kube/config

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v2

      - name: Run test
        run: |
          op --version
          op whoami
          op item list
          op vault list
          op item edit "[Lab] Jenkins (local)" --vault="Temporary" "username=jenkins"
          op item edit "[Lab] ArgoCD (local)" --vault="Temporary" "username=argocd"
