name: Github Unfollowed Nofifier

on:
  push:
    branches:
      - main
  
  schedule:
    # Runs every minutes
    - cron: '0 7 * * *'

  # Optional: You can also allow manual runs
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_OUTPUT: json

jobs:
  pre-installation:
    runs-on: ubuntu-latest
    
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3
    
    - name: Install prerequesite packages
      run: |
        sudo apt install -y jq

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
    
    - name: Configure AWS Account
      run: |
        aws configure set aws_access_key_id ${{secrets.ACCESS_KEY}}
        aws configure set aws_secret_access_key ${{secrets.ACCESS_SECRET}}
        aws configure set region $AWS_REGION
        aws configure set output $AWS_OUTPUT

    - name: List all 
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/user/followers | jq '.[].login' > crt_followers.txt
        echo Current Followers:
        cat crt_followers.txt
        
    
    - name: Download status files from S3 Bucket
      run: |
        aws s3 sync s3://github-management/follower-control/ .
        ls .
  
    - name: Show added and deleted users
      run: |
        diff -u -b saved_followers.txt crt_followers.txt  | grep '^+' | sed 's/^+//' > new_followed.txt
        diff -u -b saved_followers.txt crt_followers.txt  | grep '^-' | sed 's/^-//' > new_unfollowed.txt
        echo "NEW FOLLOWED USERS: "
        cat new_followed.txt
        echo "NEW UNFOLLOWED USERS: "
        cat new_unfollowed.txt

    - name: Check conditions and upload to S3 Bucket
      run: |
        if [ -s new_followed.txt ] || [ -s new_unfollowed.txt ]; then
            aws s3 cp crt_followers.txt s3://github-management/follower-control/saved_followers.txt --force
        else
            echo "No new or abandon followers, no action performed."
        fi

    - name: Send Email notification
      run: |
        HTML_BODY=$(cat <<EOF
        <!DOCTYPE html>
        <html>
          <head>
            <style>
              body {
                margin: 0;
                padding: 0;
                font-family: 'Arial', sans-serif;
                background: linear-gradient(to bottom, #1a1a40, #3a3a6b);
                color: #d1d1e0;
              }
              .email-container {
                max-width: 600px;
                margin: 20px auto;
                background: #282850;
                border-radius: 10px;
                overflow: hidden;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
                color: #f3f3ff;
              }
              .email-header {
                background: linear-gradient(to right, #6a1b9a, #8e24aa);
                color: #f5f5f5;
                padding: 20px;
                text-align: center;
              }
              .email-header img {
                max-height: 50px;
                margin-bottom: 10px;
                border-radius: 5px;
              }
              .email-content {
                padding: 20px;
                text-align: center;
              }
              .email-content h1 {
                font-size: 28px;
                color: #e1bee7;
                margin-bottom: 10px;
              }
              .email-content p {
                font-size: 16px;
                color: #c5cae9;
                line-height: 1.6;
              }
              .button {
                display: inline-block;
                margin-top: 20px;
                padding: 10px 20px;
                font-size: 16px;
                color: #ffffff;
                background-color: #6a1b9a;
                text-decoration: none;
                border-radius: 5px;
                box-shadow: 0 3px 5px rgba(0, 0, 0, 0.2);
                transition: background-color 0.3s ease;
              }
              .button:hover {
                background-color: #8e24aa;
              }
              .email-footer {
                background: #1e1e30;
                padding: 10px;
                text-align: center;
                font-size: 14px;
                color: #8888aa;
              }
            </style>
          </head>
          <body>
            <div class="email-container">
              <div class="email-header">
                <img src="" alt="Company Logo">
                <h2>Welcome to AWS SES</h2>
              </div>
              <div class="email-content">
                <h1>Hello, Night Owl!</h1>
                <p>
                  Experience the power of AWS Simple Email Service with this sleek night-themed email. 
                  We love the night vibes, and we hope you do too!
                </p>
                <p>
                  Click the button below to get started and explore more.
                </p>
                <a href="https://aws.amazon.com/ses" class="button">Get Started</a>
              </div>
              <div class="email-footer">
                <p>© 2024 Your Company Name. All rights reserved.</p>
              </div>
            </div>
          </body>
        </html>
        EOF
        )

        aws ses send-email \
          --from "tranhoangkhang09112001@gmail.com" \
          --destination "ToAddresses=tranhoangkhang09112001@gmail.com" \
          --message "Subject={Data=Follower Update on Github},Body={Html={Data='$HTML_BODY'}}" \
          --region us-east-1