name: "[Github] Re-Activate All Disabled Workflow Current Repo"

on:
  # Optional: You can also allow manual runs
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
          - monalisa
          - cschleiden
  push:
    branches:
      - main

  schedule:
    # Runs at 07:00 AM in every month.
    - cron: "0 7 * */1 *"

jobs:
  reactivate-disabled-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List All Workflows
        run: |
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/khangtictoc/Productive-Pipeline/actions/workflows

      - name: Enable All Workflows
        run: |
          curl -s -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/actions/workflows/WORKFLOW_ID/enable
