name: "[Github] Re-Activate All Disabled Workflow Current Repo"

on:
  push:
    branches:
      - main

  schedule:
    # Runs at 07:00 AM in every month.
    - cron: "0 7 * */1 *"

  # Optional: You can also allow manual runs
  workflow_dispatch:

jobs:
  reactivate-disabled-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequesite packages
        run: |
          sudo apt install -y jq

      - name: Fetch all workflows
        run: |
          echo "Fetching all workflows..."
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows \
            > workflows.json

          if [ ! -s workflows.json ]; then
            echo "Error: workflows.json is empty. API call failed."
            cat workflows.json
            exit 1
          fi

          echo "Workflows fetched:"
          cat workflows.json | jq '.workflows[] | {id, name, state}'

      - name: Enable all workflows
        run: |
          echo "Enabling all workflows..."
          for row in $(jq -c '.workflows[]' workflows.json); do
            ID=$(echo "$row" | jq -r '.id')
            NAME=$(echo "$row" | jq -r '.name')
            echo "Enabling: $NAME (ID: $ID)"
            curl -s -L \
              -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/$ID/enable
          done