name: Github Unfollowed Nofifier

on:
  schedule:
    # Runs every minutes
    - cron: '0 7 * * *'

  # Optional: You can also allow manual runs
  workflow_dispatch:

env:
  USERNAME: khangtictoc
  AWS_REGION: us-east-1
  AWS_OUTPUT: json

jobs:
  pre-installation:
    runs-on: ubuntu-latest
    
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3
      
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
    
    - name: Configure AWS Account
      run: |
        aws configure set aws_access_key_id ${{secrets.ACCESS_KEY}}
        aws configure set aws_secret_access_key ${{secrets.ACCESS_SECRET}}
        aws configure set region $AWS_REGION
        aws configure set output $AWS_OUTPUT

    - name: List all 
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/$USERNAME/followers 

    # - name: Show added and deleted users
    #   run: |
    #     diff -u file1.txt file2.txt | grep '^+' | sed 's/^+//' > new_followed.txt
    #     diff -u file1.txt file2.txt | grep '^-' | sed 's/^-//' > new_unfollowed.txt
    #     echo "NEW FOLLOWED USERS: "
    #     cat new_followed.txt
    #     echo "NEW UNFOLLOWED USERS: "
    #     cat new_unfollowed.txt

    # - name: Install AWS CLI
    #   run: |
        