name: "[Github] Re-Activate All Disabled Workflow Current Repo"

on:
  push:
    branches:
      - main

  schedule:
    # Runs at 07:00 AM in every month.
    - cron: "0 7 * */1 *"

  # Optional: You can also allow manual runs
  workflow_dispatch:

jobs:
  pre-installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequesite packages
        run: |
          sudo apt install -y jq

      - name: Reactivate Disabled Workflows
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/khangtictoc/Productive-Pipeline/actions/workflows
