name: Github Unfollowed Nofifier

on:
  schedule:
    # Runs every minutes
    - cron: '*/5 * * * *'

  # Optional: You can also allow manual runs
  workflow_dispatch:

jobs:
  check-os:
    runs-on: ubuntu-latest
    
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3
      
    - name: Run some action or script
      run: |
        cat /etc/os-release