name: Github Workflow Re-Activate

on:
  push:
    branches:
      - main

  schedule:
    # Runs every day
    - cron: "* * * * *"

  # Optional: You can also allow manual runs
  workflow_dispatch:

jobs:
  pre-installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequesite packages
        run: |
          sudo apt install -y jq

      - name: Install AWS CLI
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/khangtictoc/Productive-Pipeline/actions/workflows
