name: "[K8s] OSS Installation"

on:
  # push:
  #   branches:
  #     - main

  # schedule:
  #   # Runs at 07:00 AM in every month.
  #   - cron: "0 17 */1 * *"

  # Optional: You can also allow manual runs
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: "Choose cloud platform for AKS/EKS"
        required: true
        default: "azure"
        type: choice
        options:
          - azure
          - aws
      region_aws:
        description: "Choose region for EKS"
        required: true
        default: "eastus"
        type: choice
        options:
          - us-east-1
          - us-west-2
          - ap-east-1

      region_azure:
        description: "Choose region for AKS"
        required: true
        default: "Japan East"
        type: choice
        options:
          - East US
          - West US 2
          - Japan East
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
          - stg
      terraform_action:
        description: "Choose Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - plan
          - apply
          - plan & apply
          - plan --destroy
          - destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  verify-configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Secret
        run: |
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:4}****"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:0:4}****"

      - name: Verify Input
        run: |
          echo "Verify input"

  kubernetes-cloud-action:
    runs-on: ubuntu-latest

    steps:
      - name: Install Kubectl
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/kubectl.sh | sh

      - name: Set up Cluster Access Credentials
        run: |
          aws s3 cp "s3://terragrunt-output/dev/azure/Japan East/kubeconfig" ~/.kube/config

      - name: Clone OSS Repository
        run: |
          git clone https://github.com/khangtictoc/ArgoCD-Apps.git "OSS"

      - name: "[K8S] Install ArgoCD"
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/ArgoCD-Apps/refs/heads/main/helm/argocd/install.sh | sh
      
      - name: "[CLI] Install ArgoCD"
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/ArgoCD-Apps/refs/heads/main/helm/argocd/argocd_cli.sh | sh

      - name: "Install Pre-requisite"
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/ArgoCD-Apps/refs/heads/main/script/create_namespace.sh | sh
      - name: "[K8S] Install NGINX Ingress Controller"
        working-directory: OSS/argocd_apps/nginx
        run: |
          kubectl apply -f applications.yaml

      - name: "[K8S] Install JENKINS"
        working-directory: OSS/argocd_apps/jenkins
        run: |
          kubectl apply -f applications.yaml
