name: "[Terraform] Destroy Kubernetes Lab for Azure/AWS"

on:
  # push:
  #   branches:
  #     - main

  # schedule:
  #   # Runs at 07:00 AM in every month.
  #   - cron: "0 23 */1 * *"

  # Optional: You can also allow manual runs
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: "Choose cloud platform for AKS/EKS"
        required: true
        default: "azure"
        type: choice
        options:
          - azure
          - aws

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  kubernetes-cloud-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          if ! command -v aws 2>&1 >/dev/null
          then
              echo "- [NOTIFY 🔔] aws command could not be found. Please install it first."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          else
              echo "- [CHECKED ✅] aws exists"
          fi

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.10.3/terraform_1.10.3_linux_amd64.zip
          unzip terraform_1.10.3_linux_amd64.zip
          sudo mv terraform /usr/local/bin/terraform
          echo "==== CLEAN UP ===="
          rm -f terraform_1.10.3_linux_amd64.zip

      - name: Install prerequesite packages
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.71.2-alpha2024122002/terragrunt_linux_amd64
          sudo chmod u+x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Check Out Terragrunt Project
        run: |
          git clone --depth 1 https://github.com/khangtictoc/Terragrunt_Project_Structure_Design.git

      - name: Terragrunt Destroy
        run: |
          cd "Terragrunt_Project_Structure_Design/environment/dev/azure/Korea South/aks"
          terragrunt destroy -auto-approve
