name: "Terraform - Kubernetes Cloud Lab"

on:
  # push:
  #   branches:
  #     - main

  # schedule:
  #   # Runs at 07:00 AM in every month.
  #   - cron: "0 17 */1 * *"

  # Optional: You can also allow manual runs
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: "Choose cloud platform for AKS/EKS"
        required: true
        default: "azure"
        type: choice
        options:
          - azure
          - aws
          - gcp
      region_aws:
        description: "Choose region for EKS"
        required: true
        default: "us-east-1"
        type: choice
        options:
          - us-east-1
          - us-west-2
          - ap-east-1

      region_azure:
        description: "Choose region for AKS"
        required: true
        default: "Japan East"
        type: choice
        options:
          - East US
          - West US 2
          - Japan East
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
          - stg
      terraform_action:
        description: "Choose Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - plan
          - apply
          - plan & apply
          - plan --destroy
          - destroy

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: ${{ github.event.inputs.cloud_provider == 'aws' && github.event.inputs.region_aws || github.event.inputs.region_azure }}

jobs:
  verify-configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Secret
        run: |
          echo "ARM_TENANT_ID: ${ARM_TENANT_ID:0:4}****"
          echo "ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID:0:4}****"
          echo "ARM_CLIENT_ID: ${ARM_CLIENT_ID:0:4}****"
          echo "ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET:0:4}****"
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:4}****"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:0:4}****"

      - name: Verify Input
        run: |
          echo "Cloud Provider: ${{ github.event.inputs.cloud_provider }}"
          echo "Region: $REGION"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Terraform Action: ${{ github.event.inputs.terraform_action }}"

  cloud-k8s-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/aws_cli.sh | sh

      - name: Install Terraform
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/terraform.sh | sh

      - name: Install Terragrunt CLI
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/terragrunt.sh | sh

      - name: Check Out Terragrunt Project
        run: |
          git clone --depth 1 https://github.com/khangtictoc/Terragrunt_Project_Structure_Design.git

      - name: Terragrunt Plan
        if: contains(github.event.inputs.terraform_action, 'plan')
        run: |
          cd "Terragrunt_Project_Structure_Design/environment/${{ github.event.inputs.environment }}/${{ github.event.inputs.cloud_provider }}/$REGION"
          terragrunt run-all plan --non-interactive \
            --queue-include-external \
            --working-dir . \
            --queue-include-dir aks \
            --queue-include-dir appgw \
            --queue-include-dir naming

      - name: Terragrunt Apply (Auto Approve)
        if: contains(github.event.inputs.terraform_action, 'apply')
        run: |
          cd "Terragrunt_Project_Structure_Design/environment/${{ github.event.inputs.environment }}/${{ github.event.inputs.cloud_provider }}/$REGION"
          terragrunt run-all apply --non-interactive \
            --queue-include-external \
            --working-dir . \
            --queue-include-dir aks \
            --queue-include-dir appgw \
            --queue-include-dir naming

      - name: Terragrunt Destroy (Auto Approve)
        if: github.event.inputs.terraform_action == 'destroy'
        run: |
          cd "Terragrunt_Project_Structure_Design/environment/${{ github.event.inputs.environment }}/${{ github.event.inputs.cloud_provider }}/$REGION"
          terragrunt run-all destroy --non-interactive \
            --queue-include-external \
            --working-dir . \
            --queue-include-dir aks \
            --queue-include-dir appgw \
            --queue-include-dir naming

      - name: Terragrunt Plan Destroy
        if: github.event.inputs.terraform_action == 'plan --destroy'
        run: |
          cd "Terragrunt_Project_Structure_Design/environment/${{ github.event.inputs.environment }}/${{ github.event.inputs.cloud_provider }}/$REGION"
          terragrunt run-all plan --destroy --non-interactive \
            --queue-include-external \
            --working-dir . \
            --queue-include-dir aks \
            --queue-include-dir appgw \
            --queue-include-dir naming
