name: "[Terraform] Spin up Kubernetes Lab for Azure/AWS"

on:
  # push:
  #   branches:
  #     - main

  # schedule:
  #   # Runs at 07:00 AM in every month.
  #   - cron: "0 17 */1 * *"

  # Optional: You can also allow manual runs
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: "Choose cloud platform for AKS/EKS"
        required: true
        default: "azure"
        type: choice
        options:
          - azure
          - aws

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  kubernetes-cloud-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/aws_cli.sh | sh

      - name: Install Terraform
        run: |
          curl -sS https://raw.githubusercontent.com/khangtictoc/Productive-Workspace-Set-Up/refs/heads/main/linux/installation/developer-packages/ubuntu/tools/terraform.sh | sh

      - name: Install prerequesite packages
        run: |
          if ! command -v terragrunt 2>&1 >/dev/null
            then
              wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.71.2-alpha2024122002/terragrunt_linux_amd64
              sudo chmod u+x terragrunt_linux_amd64
              sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          else
              echo "- [CHECKED ✅] terragrunt command exists"
          fi

      - name: Check Out Terragrunt Project
        run: |
          git clone --depth 1 https://github.com/khangtictoc/Terragrunt_Project_Structure_Design.git

      - name: Terragrunt Plan
        run: |
          cd "Terragrunt_Project_Structure_Design/environment/dev/azure/Korea South/aks"
          terragrunt plan

      - name: Terragrunt Apply (Auto Approve)
        run: |
          cd "Terragrunt_Project_Structure_Design/environment/dev/azure/Korea South/aks"
          terragrunt apply --auto-approve
